# Generated by Django 4.2.2 on 2024-08-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0002_rename_clients_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Ф.И.О"),
        ),
    ]
