# Generated by Django 4.2.2 on 2024-08-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0004_alter_message_body_letter_alter_message_title_letter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body_letter",
            field=models.TextField(blank=True, null=True, verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="message",
            name="title_letter",
            field=models.CharField(max_length=100, verbose_name="Тема"),
        ),
    ]
