# Generated by Django 4.2.2 on 2024-08-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0005_alter_message_body_letter_alter_message_title_letter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="status",
            field=models.CharField(
                choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                default="FAILURE",
                max_length=50,
                verbose_name="Статус попытки",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("Раз в день", "Раз в день"),
                    ("Раз в неделю", "Раз в неделю"),
                    ("Раз в месяц", "Раз в месяц"),
                ],
                default="Раз в день",
                max_length=50,
                verbose_name="Периодичность рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="status",
            field=models.CharField(
                choices=[
                    ("Завершена", "Завершена"),
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                ],
                default="Создана",
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
