# Generated by Django 4.2.2 on 2024-08-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0008_alter_attempt_date_time_last_attempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="mail_server_response",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ответ почтового сервера"
            ),
        ),
    ]
