# Generated by Django 4.2.2 on 2024-08-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0009_alter_attempt_mail_server_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglist",
            name="date_and_time_of_sending",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата и время первой отправки отправки",
            ),
        ),
    ]
