# Generated by Django 4.2.2 on 2024-08-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0011_alter_mailinglist_date_and_time_of_sending"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglist",
            name="next_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата и время следующей отправки отправки",
            ),
        ),
    ]
