# Generated by Django 4.2.2 on 2024-09-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0017_alter_mailinglist_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attempt",
            options={
                "ordering": ("id",),
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
            },
        ),
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ("id",),
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="mailinglist",
            options={
                "ordering": ("id",),
                "permissions": [("can_edit_status", "can_edit_status")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ("id",),
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
